kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-workspace
  namespace: vadym
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
