apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-piipeline-template
spec:
  resourcetemplates:
    - aapiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-pipeline-run-
        namespace: vadym
      spec:
        pipelineRef:
          name: ci-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: tekton-workspace
          - name: app-repo-secret
            secret:
              secretName: gh-apps-ssh-key
