apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: vadym
spec:
  params:
    - name: app-repo-url
      type: string
      default: https://github.com/VadimDez/apps-ab.git
    - name: app-repo-private-key
      type: string
      default: '""'

  workspaces:
    - name: shared-workspace
    - name: app-repo-secret

  tasks:
    - name: clone-app-repo
      params:
        - name: url
          value: $(params.app-repo-url)
        - name: subdirectory
          value: is-source
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: app-repo-secret
          workspace: app-repo-secret

    - name: resolve-props
      params:
        - name: is-source-directory
          value: is-source
      runAfter:
        - clone-app-repo
      taskRef:
        kind: Task
        name: resolve-props
      workspaces:
        - name: input
          workspace: shared-workspace
