apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: vadym
spec:
  params:
    - name: app-repo-url
      type: string
      default: https://github.com/VadimDez/apps-ab.git
    - name: app-repo-private-key
      type: string
      default: '""'
    - default: ""
      name: app-directory
      type: string

  workspaces:
    - name: shared-workspace
    - name: app-repo-secret

  tasks:
    - name: clone-app-repo
      params:
        - name: url
          value: $(params.app-repo-url)
        - name: subdirectory
          value: $(params.app-directory)
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: app-repo-secret
          workspace: app-repo-secret
