apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-bar
spec:
  params:
    - name: is-source-directory
      type: string
      description: directory where ACE source is located, relative to workspace
    - name: is-application-names
      type: string
      description: name list of bars
    - name: is-projects
      type: array
      description: array of arrays - list of projects

  steps:
    - image: icr.io/appc-dev/ace-server:12.0.2.0-r2-20211115-123200-amd64
      name: generate-bar
      args:
        - $(params.is-projects[*])
      script: |
        #!/usr/bin/env bash

        echo "=============="
        echo "${params.is-application-names}"
        echo "=============="

        function deserialize_array() {
          IFS="${3:-$'\x01'}" read -r -a "${2}" <<<"${!1}" # -a => split on IFS
        }

        rm -rf $(workspaces.workspace.path)/bars
        mkdir -p $(workspaces.workspace.path)/bars

        . /opt/ibm/ace-12/server/bin/mqsiprofile

        ls $(workspaces.workspace.path)/bars/

        for integrationServer in $@; do
          deserialize_array integrationServer barsArray '|'

          for barIndex in "${!barsArray[@]}"; do
            # clear source folder
            rm -rf $(workspaces.workspace.path)/source
            mkdir $(workspaces.workspace.path)/source
            project_options=""

            echo "barIndex: ${barIndex}"
            echo "barsList: ${barsArray[barIndex]}"

            deserialize_array barsArray[barIndex] projects ';'
            declare -p projects

            for project in "${projects[@]}"; do
                echo "project in bar list: ${project}"
                mkdir $(workspaces.workspace.path)/source/${project}
                cp -r $(workspaces.workspace.path)/$(params.is-source-directory)/${project} $(workspaces.workspace.path)/source/${project}
                project_options="--project ${project} ${project_options}"
            done

            # list copied folders
            ls $(workspaces.workspace.path)/source

          done
        done

        ls $(workspaces.workspace.path)/bars/
  workspaces:
    - name: workspace
