apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-bar
spec:
  params:
    - name: is-source-directory
      type: string
      description: directory where ACE source is located, relative to workspace
    - name: is-application-names
      type: array
      description: name list of the application
    - name: is-projects
      type: array
      description: array of arrays - list of projects

  steps:
    - image: icr.io/appc-dev/ace-server:12.0.2.0-r2-20211115-123200-amd64
      name: generate-bar
      script: |
        #!/usr/bin/env bash


        rm -rf $(workspaces.workspace.path)/bars
        mkdir -p $(workspaces.workspace.path)/bars
        rm -rf $(workspaces.workspace.path)/source

        echo "$(params.is-projects[@])"
  workspaces:
    - name: workspace
