apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-projects-to-clone
spec:
  params:
    - name: isServerList
      default: []
      description: Aray of IntegrationServer yamls
      type: array
    - name: config-repo-dirname
      type: string
  results:
    - name: projects
      type: array
  steps:
    - name: parse-source-properties
      image: image-registry.openshift-image-registry.svc:5000/vadym/sh-tools
      args:
        - $(params.isServerList[*])
      script: |
        #!/usr/bin/env bash
        set -ex

        projects=()

        extract_projects() {
          yaml_file=$1
          new_projects=$(yq e '.metadata.annotations.ab-bars[].projects[]' "$yaml_file" 2>/dev/null)
          
          if [ -n "$new_projects" ]; then
              # Add the extracted projects to the array variable
              projects+=($new_projects)
          fi
        }

        for file in $@; do
          integration_server_yaml_path="$(workspaces.input.path)/$(params.config-repo-dirname)/$file"
          extract_projects $integration_server_yaml_path
        done

        # Output the array to the results variable
        printf -v projectsString '%s,' "${projects[@]}"
        projectsString="${projectsString%,}"  # Remove the trailing comma
        echo "projects=[${projectsString}]" >> $(results.projects.path)
  workspaces:
    - name: input
