apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nexus-download
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: CLI
    tekton.dev/tags: search
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    This task performs curl operation to transfer data from internet.

  params:
    - name: nexus-user
      description: User for Nexus
      type: string
    - name: nexus-password
      description: Password for Nexus
      type: string
    - name: nexus-url
      description: "Nexus Repository URL: http://domain only"
      type: string
      default: http://vadym-nexusrepo-sonatype-nexus-service.vadym.svc.cluster.local:8081
    - name: nexus-repo
      description: "Nexus Folder"
      default: vadym
      type: string
    - name: CHANGE_REQUEST
      description: "Change request value"
      type: string

  steps:
    - name: curl
      image: docker.io/curlimages/curl:7.72.0@sha256:bd5bbd35f89b867c1dccbc84b8be52f3f74dea20b46c5fe0db3780e040afcb6f
      workingDir: $(workspaces.workspace.path)
      env:
        - name: NEXUS_USER
          value: $(params.nexus-user)
        - name: NEXUS_PASSWORD
          value: $(params.nexus-password)
        - name: NEXUS_URL
          value: $(params.nexus-url)
        - name: NEXUS_REPO
          value: $(params.nexus-repo)
        - name: CHANGE_REQUEST
          value: $(params.CHANGE_REQUEST)
      script: |
        #!/bin/sh

        rm -rf $CHANGE_REQUEST
        mkdir $CHANGE_REQUEST
        mkdir -p "$(workspaces.workspace.path)/$NEXUS_REPO"
        cd $CHANGE_REQUEST
        ls
        echo "BEFORE ==================================="
        # Loop through each file in the Nexus directory and download
        for file in $(curl -s -u "${NEXUS_USER}:${NEXUS_PASSWORD}" -X GET "${NEXUS_URL}/service/rest/v1/components/?repository=${NEXUS_REPO}" | grep -o '"downloadUrl" *: *"[^"]*"' | sed 's/^.*: "\(.*\)".*$/\1/' | sed -n "/\/${NEXUS_REPO}\/${CHANGE_REQUEST}/p"); do
            echo $file
            filename=$(basename "${file}")
            
            relative_path=$(echo "$file" | sed "s|$NEXUS_URL/repository/$NEXUS_REPO/$CHANGE_REQUEST||")

            echo "relative path: $relative_path"
            
            # Create directories locally if they don't exist
            mkdir -p "$(workspaces.workspace.path)/$(dirname "${relative_path}")"

            curl -u "${NEXUS_USER}:${NEXUS_PASSWORD}"  -o "$(workspaces.workspace.path)/${relative_path}" -O -J -L "${file}"
        done
        echo "AFTER ==================================="
        ls
  workspaces:
    - name: workspace
