apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: resolve-props
spec:
  params:
    - name: is-source-directory
  results:
    - name: registry-host
  steps:
    - name: resolve-ocp-properties
      image: quay.io/openshift/origin-cli:latest
      script: |

        echo -n $(oc registry info) > $(results.registry-host.path)

  workspaces:
    - name: input
